// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Process = require("process");
var Typescript = require("typescript");

var fileNames = Process.argv.slice(2);

console.log(fileNames);

var sf = Typescript.createSourceFile("./types.d.ts", "interface Process {\n      argv: string[];\n      test: any;\n  }", "ESNext", false);

sf.forEachChild(function (child) {
      console.log(child.kind);
      
    });

exports.fileNames = fileNames;
exports.sf = sf;
/* fileNames Not a pure module */
