// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Parser = require("./parser.bs.js");
var Process = require("process");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Typescript = require("typescript");

var fileNames = Process.argv.slice(2);

console.log(fileNames);

console.log(Caml_array.get(Typescript.SyntaxKind, 0));

Parser.parse("./types.d.ts", "interface Process {\n      argv: string[];\n      test: any;\n  }");

console.log("RX");

exports.fileNames = fileNames;
/* fileNames Not a pure module */
