// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var TypeScript = require("./TypeScript.bs.js");
var Typescript = require("typescript");

function tsToResType(_node) {
  while(true) {
    var node = _node;
    console.log(node.kind);
    var match = TypeScript.SyntaxKind.tFromJs(node.kind);
    switch (match) {
      case /* Identifier */0 :
          console.log(node.text);
          return ;
      case /* InterfaceDeclaration */1 :
          _node = node.name;
          continue ;
      case /* SourceFile */2 :
          console.log(node.statements.length);
          node.statements.forEach(tsToResType);
          return ;
      
    }
  };
}

function parse(fileName, source) {
  return tsToResType(Typescript.createSourceFile(fileName, source, Typescript.ScriptTarget.ES2015, false));
}

exports.tsToResType = tsToResType;
exports.parse = parse;
/* typescript Not a pure module */
